packages:
  - examples/*
  - packages/*
  - docs
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript
  - unrs-resolver
overrides:
  esbuild: ^0.27.2
